"""Mutable HTF Fib strategy config for autosearch.

Maps to ``scripts.run_htf_fib_backtest.StrategyConfig``. Keep a change only when
``research.htf_fib_autosearch.evaluate_htf_fib_config`` reports verdict KEEP and
an improved score.

Combo ids are defined in ``docs/research/HTF_FIB_TOOL_COMBINATIONS_2026-07.md``.
Order-flow and full volume-profile are intentionally absent.
"""

from __future__ import annotations

# Baseline control: hardened MTF without sweep/AVWAP.
CONFIG: dict = {
    "combo_id": "hardened_mtf",
    "fib_timeframe": "4h",
    "left_bars": 5,
    "right_bars": 5,
    "rsi_long": 30.0,
    "rsi_short": 70.0,
    "require_mtf_rsi": True,
    "require_ema_stack": True,
    "require_candle": True,
    "invalidate_swing": True,
    "one_entry_per_swing": True,
    "require_liquidity_sweep": False,
    "require_anchored_vwap": False,
    "atr_period": 14,
    "tp_atr": 1.5,
    "sl_atr": 1.5,
    "max_hold_bars": 32,
    "fib_zone": "golden",
    "invalidate_mode": "wick",
}

# Preregistered partial stacks (evaluated every search; also perturbable via combo_id).
# Hardened_* mirrors the locked archive control (often zero trades).
# Soft_* keeps Fib + EMA200-style directional bias with lighter RSI so tool gates
# can be ranked when hardened stacks are sparse — still no order-flow / VP.
COMBOS: dict[str, dict] = {
    "hardened_mtf": {
        "rsi_long": 30.0,
        "rsi_short": 70.0,
        "require_mtf_rsi": True,
        "require_ema_stack": True,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": False,
        "require_anchored_vwap": False,
    },
    "hardened_sweep": {
        "rsi_long": 30.0,
        "rsi_short": 70.0,
        "require_mtf_rsi": True,
        "require_ema_stack": True,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": True,
        "require_anchored_vwap": False,
    },
    "hardened_avwap": {
        "rsi_long": 30.0,
        "rsi_short": 70.0,
        "require_mtf_rsi": True,
        "require_ema_stack": True,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": False,
        "require_anchored_vwap": True,
    },
    "hardened_sweep_avwap": {
        "rsi_long": 30.0,
        "rsi_short": 70.0,
        "require_mtf_rsi": True,
        "require_ema_stack": True,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": True,
        "require_anchored_vwap": True,
    },
    "soft_baseline": {
        "rsi_long": 45.0,
        "rsi_short": 55.0,
        "require_mtf_rsi": False,
        "require_ema_stack": False,
        "require_candle": True,
        "invalidate_swing": False,
        "one_entry_per_swing": False,
        "require_liquidity_sweep": False,
        "require_anchored_vwap": False,
        "tp_atr": 2.0,
        "sl_atr": 2.0,
        "max_hold_bars": 64,
        "left_bars": 5,
        "right_bars": 2,
    },
    "soft_sweep": {
        "rsi_long": 45.0,
        "rsi_short": 55.0,
        "require_mtf_rsi": False,
        "require_ema_stack": False,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": True,
        "require_anchored_vwap": False,
        "tp_atr": 2.0,
        "sl_atr": 2.0,
        "max_hold_bars": 64,
        "left_bars": 5,
        "right_bars": 2,
    },
    "soft_avwap": {
        "rsi_long": 45.0,
        "rsi_short": 55.0,
        "require_mtf_rsi": False,
        "require_ema_stack": False,
        "require_candle": True,
        "invalidate_swing": False,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": False,
        "require_anchored_vwap": True,
        "tp_atr": 2.0,
        "sl_atr": 2.0,
        "max_hold_bars": 64,
        "left_bars": 5,
        "right_bars": 2,
    },
    "soft_sweep_avwap": {
        "rsi_long": 45.0,
        "rsi_short": 55.0,
        "require_mtf_rsi": False,
        "require_ema_stack": False,
        "require_candle": True,
        "invalidate_swing": True,
        "one_entry_per_swing": True,
        "require_liquidity_sweep": True,
        "require_anchored_vwap": True,
        "tp_atr": 2.0,
        "sl_atr": 2.0,
        "max_hold_bars": 64,
        "left_bars": 5,
        "right_bars": 2,
    },
}

PARAM_SPACE: dict[str, list] = {
    "combo_id": list(COMBOS.keys()),
    "fib_timeframe": ["4h", "1d"],
    "left_bars": [2, 3, 5, 7],
    "right_bars": [2, 3, 5, 7],
    "rsi_long": [25.0, 30.0, 35.0, 40.0, 45.0, 50.0],
    "rsi_short": [50.0, 55.0, 60.0, 65.0, 70.0, 75.0],
    "atr_period": [10, 14, 21],
    "tp_atr": [1.0, 1.5, 2.0, 2.5, 3.0],
    "sl_atr": [1.0, 1.5, 2.0, 2.5, 3.0],
    "max_hold_bars": [16, 32, 48, 64, 96, 128],
    "fib_zone": ["golden", "mid", "wide", "shallow"],
    "invalidate_mode": ["none", "wick", "close"],
    "require_candle": [True, False],
    "one_entry_per_swing": [True, False],
}

# Named refinement rounds for iterative search (distinct searchable spaces).
REFINEMENT_ROUNDS: list[dict] = [
    {
        "id": "R1_zone_volume",
        "description": (
            "Widen Fib entry bands (golden/mid/wide/shallow) and soft RSI; "
            "raise informative trade count without new AND filters."
        ),
        "seed_config": {
            "combo_id": "soft_baseline",
            "fib_zone": "wide",
            "invalidate_mode": "none",
            "invalidate_swing": False,
            "one_entry_per_swing": False,
            "require_candle": False,
            "require_mtf_rsi": False,
            "require_ema_stack": False,
            "rsi_long": 45.0,
            "rsi_short": 55.0,
            "tp_atr": 2.0,
            "sl_atr": 2.0,
            "max_hold_bars": 64,
            "left_bars": 5,
            "right_bars": 2,
            "fib_timeframe": "4h",
            "atr_period": 14,
        },
        "param_space": {
            "combo_id": ["soft_baseline", "soft_avwap"],
            "fib_zone": ["golden", "mid", "wide", "shallow"],
            "fib_timeframe": ["4h", "1d"],
            "left_bars": [2, 3, 5, 7],
            "right_bars": [2, 3, 5],
            "rsi_long": [40.0, 45.0, 50.0],
            "rsi_short": [50.0, 55.0, 60.0],
            "require_candle": [True, False],
            "one_entry_per_swing": [True, False],
            "tp_atr": [1.5, 2.0, 2.5],
            "sl_atr": [1.5, 2.0, 2.5],
            "max_hold_bars": [32, 64, 96],
            "atr_period": [14],
        },
        "iters": 40,
    },
    {
        "id": "R2_exits",
        "description": (
            "Exit/hold grid on soft wide-zone family: TP/SL ATR mults and max hold; "
            "candle on/off. Distinct from R1 zone focus."
        ),
        "seed_config": {
            "combo_id": "soft_baseline",
            "fib_zone": "wide",
            "invalidate_mode": "none",
            "invalidate_swing": False,
            "one_entry_per_swing": False,
            "require_candle": False,
            "require_mtf_rsi": False,
            "require_ema_stack": False,
            "rsi_long": 45.0,
            "rsi_short": 55.0,
            "tp_atr": 2.0,
            "sl_atr": 1.5,
            "max_hold_bars": 48,
            "left_bars": 5,
            "right_bars": 2,
            "fib_timeframe": "4h",
            "atr_period": 14,
        },
        "param_space": {
            "combo_id": ["soft_baseline"],
            "fib_zone": ["mid", "wide"],
            "tp_atr": [1.0, 1.5, 2.0, 2.5, 3.0, 4.0],
            "sl_atr": [1.0, 1.5, 2.0, 2.5, 3.0],
            "max_hold_bars": [16, 24, 32, 48, 64, 96, 128],
            "require_candle": [True, False],
            "atr_period": [10, 14, 21],
            "rsi_long": [40.0, 45.0, 50.0],
            "rsi_short": [50.0, 55.0, 60.0],
            "left_bars": [3, 5],
            "right_bars": [2, 3, 5],
        },
        "iters": 50,
    },
    {
        "id": "R3_structure",
        "description": (
            "Invalidation mode (none/wick/close) + one-entry + EMA stack toggle "
            "on soft mid/wide zones; structural A/B vs prior rounds."
        ),
        "seed_config": {
            "combo_id": "soft_baseline",
            "fib_zone": "mid",
            "invalidate_mode": "close",
            "invalidate_swing": True,
            "one_entry_per_swing": True,
            "require_candle": True,
            "require_mtf_rsi": False,
            "require_ema_stack": False,
            "rsi_long": 45.0,
            "rsi_short": 55.0,
            "tp_atr": 2.0,
            "sl_atr": 2.0,
            "max_hold_bars": 64,
            "left_bars": 5,
            "right_bars": 2,
            "fib_timeframe": "4h",
            "atr_period": 14,
        },
        "param_space": {
            "combo_id": ["soft_baseline", "soft_avwap", "soft_sweep"],
            "fib_zone": ["golden", "mid", "wide"],
            "invalidate_mode": ["none", "wick", "close"],
            "one_entry_per_swing": [True, False],
            "require_candle": [True, False],
            "require_ema_stack": [True, False],
            "tp_atr": [1.5, 2.0, 2.5, 3.0],
            "sl_atr": [1.5, 2.0, 2.5],
            "max_hold_bars": [32, 64, 96],
            "rsi_long": [35.0, 40.0, 45.0],
            "rsi_short": [55.0, 60.0, 65.0],
            "left_bars": [3, 5, 7],
            "right_bars": [2, 3, 5],
        },
        "iters": 50,
    },
]
